config/routes.rb
Restaurant::Application.routes.draw do
  resources :posts

  resources :betasignups
  
  root :to => 'betasignups#new'

end

app/models/betasignup.rb
class Betasignup < ActiveRecord::Base
  attr_accessible :email
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/betasignups_controller.rb
class BetasignupsController < ApplicationController
  # GET /betasignups
  # GET /betasignups.json
  def index
    @betasignups = Betasignup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @betasignups }
    end
  end

  # GET /betasignups/1
  # GET /betasignups/1.json
  def show
    @betasignup = Betasignup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @betasignup }
    end
  end

  # GET /betasignups/new
  # GET /betasignups/new.json
  def new
    @betasignup = Betasignup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @betasignup }
    end
  end

  # GET /betasignups/1/edit
  def edit
    @betasignup = Betasignup.find(params[:id])
  end

  # POST /betasignups
  # POST /betasignups.json
  def create
    @betasignup = Betasignup.new(params[:betasignup])

    respond_to do |format|
      if @betasignup.save
        BetaMailer.beta_signup(@betasignup).deliver
        format.html { redirect_to @betasignup, notice: 'Betasignup was successfully created.' }
        format.json { render json: @betasignup, status: :created, location: @betasignup }
      else
        format.html { render action: "new" }
        format.json { render json: @betasignup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /betasignups/1
  # PUT /betasignups/1.json
  def update
    @betasignup = Betasignup.find(params[:id])

    respond_to do |format|
      if @betasignup.update_attributes(params[:betasignup])
        format.html { redirect_to @betasignup, notice: 'Betasignup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @betasignup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /betasignups/1
  # DELETE /betasignups/1.json
  def destroy
    @betasignup = Betasignup.find(params[:id])
    @betasignup.destroy

    respond_to do |format|
      format.html { redirect_to betasignups_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/betasignups_helper.rb
module BetasignupsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/betasignups/_form.html.erb
<%= form_for(@betasignup) do |f| %>
  <% if @betasignup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@betasignup.errors.count, "error") %> prohibited this betasignup from being saved:</h2>

      <ul>
      <% @betasignup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :email, :placeholder => 'Your email' %> <%= f.submit 'Signup', :class => 'btn btn-danger', :id => 'submitbeta' %>
  </div>
<% end %>

app/views/betasignups/edit.html.erb
<h1>Editing betasignup</h1>

<%= render 'form' %>

<%= link_to 'Show', @betasignup %> |
<%= link_to 'Back', betasignups_path %>

app/views/betasignups/index.html.erb
<% @betasignups.each do |betasignup| %>
  <tr>
    <td><%= betasignup.email %></td>
    <td><%= link_to 'Show', betasignup %></td>
    <td><%= link_to 'Edit', edit_betasignup_path(betasignup) %></td>
    <td><%= link_to 'Destroy', betasignup, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Betasignup', new_betasignup_path %>

app/views/betasignups/new.html.erb
<p id="uvp">Attract customers to your restaurant with a beautiful and functional website.</p><br/>

<p>Signup and we'll let you know as soon as we launch!</p><br/>
<%= render 'form' %>

app/views/betasignups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @betasignup.email %>
</p>


<%= link_to 'Edit', edit_betasignup_path(@betasignup) %> |
<%= link_to 'Back', betasignups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE htmlPUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN""http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
  <title>Restaurant</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "custom"     , :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Simonetta:400,400italic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=The+Girl+Next+Door' rel='stylesheet' type='text/css'>
</head>
<body>
	<div id="navbar">
		<h1 id="logo">SugarCider</h1><br/>
		<ul>
			<li><%= link_to 'Blog', posts_path %></li>
			<li><%= link_to 'Our Product', '/' %>
		</ul>
	</div>
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<ul>
<% @posts.each do |post| %>
    <li><%= post.title %></li>
    <li><%= post.body %></li>
    <li><%= link_to 'Show', post %></li>
    <li><%= link_to 'Edit', edit_post_path(post) %></li>
    <li><%= link_to 'Destroy', post, confirm: 'Are you sure?', method: :delete %></li>
<% end %>
</ul>
<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Body:</b>
  <%= @post.body %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>